# Auto-generated by CloudVolley AI agent
from __future__ import annotations
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.operators.empty import EmptyOperator

DEFAULT_ARGS = {
    "owner": "cloudvolley",
    "depends_on_past": False,
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    dag_id="tst_pipeline",
    default_args=DEFAULT_ARGS,
    description="Auto-generated pipeline for tst_pipeline",
    schedule_interval="@daily",
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=["tst_pipeline", "generated"],
) as dag:

    start = EmptyOperator(task_id="start")

    def extract(**ctx):
        print(f"[tst_pipeline] Extracting for {ctx['ds']}")
        return {"rows": 1000}

    def transform(**ctx):
        rows = ctx["ti"].xcom_pull(task_ids="extract")["rows"]
        print(f"[tst_pipeline] Transforming {rows} rows")
        return {"rows": rows, "status": "ok"}

    def load(**ctx):
        upstream = ctx["ti"].xcom_pull(task_ids="transform")
        print(f"[tst_pipeline] Loading {upstream['rows']} rows")

    t_extract   = PythonOperator(task_id="extract",   python_callable=extract)
    t_transform = PythonOperator(task_id="transform", python_callable=transform)
    t_load      = PythonOperator(task_id="load",      python_callable=load)
    end         = EmptyOperator(task_id="end")

    start >> t_extract >> t_transform >> t_load >> end
